spring.application.name=discovery-service
server.port=8084

# ==========================================
# CONEXI\u00D3N A NEO4J (Grafos)
# ==========================================
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=password123