spring.config.import=optional:file:.env.properties
spring.application.name=identity-service
server.port=8080
# ==========================================
# 1. CONEXION A POSTGRESQL (Relacional)
# ==========================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/tap2eat_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# Esto hace que Java cree las tablas automaticamente
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate: Esto hace que Java cree y actualice las tablas autom\u00E1ticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CORS Configuration
tap2eat.cors.allowed-origins=http://localhost:4200,file://

jwt.expiration=${JWT_EXPIRATION:120000}