spring.application.name=identity-service
server.port=8081
# ==========================================
# 1. CONEXION A POSTGRESQL (Relacional)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/tap2eat_db
spring.datasource.username=admin
spring.datasource.password=password123
# Esto hace que Java cree las tablas automaticamente
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate: Esto hace que Java cree y actualice las tablas autom\u00E1ticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

