spring.application.name=finance-service
server.port=8083

# ==========================================
# CONEXI\u00D3N A POSTGRESQL (Relacional - Finanzas)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/tap2eat_finance
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update