spring.application.name=catalog-service
server.port=8082

tap2eat.cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
tap2eat.cloudinary.api-key=${CLOUDINARY_API_KEY:}
tap2eat.cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
tap2eat.cloudinary.product-folder=tap2eat/products

catalog.images.default-product-url=${DEFAULT_PRODUCT_IMAGE_URL:}
catalog.images.default-product-object-key=${DEFAULT_PRODUCT_IMAGE_OBJECT_KEY:tap2eat/defaults/default-product}
tap2eat.images.default-product.provider=CLOUDINARY

spring.security.oauth2.resourceserver.jwt.public-key-location=${JWT_PUBLIC_KEY_LOCATION:classpath:keys/public_key.pem}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.mongodb.uri=mongodb://admin:password123@mongodb:27017/tap2eat_mongo?authSource=admin

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

postal-code.api.base-url=${POSTAL_CODE_API_BASE_URL:https://api.copomex.com/query}
postal-code.api.token=${POSTAL_CODE_API_TOKEN:pruebas}
postal-code.api.type=${POSTAL_CODE_API_TYPE:simplified}

tap2eat.catalog.time-zone=America/Mexico_City
tap2eat.internal.service-token=${INTERNAL_SERVICE_TOKEN:tap2eat-internal-dev-token}
