spring.application.name=catalog-service
server.port=8082

# ==========================================
# CONEXI\u00D3N A MONGODB (Documental)
# ==========================================
spring.data.mongodb.uri=mongodb://admin:password123@localhost:27017/tap2eat_mongo?authSource=admin