// <auto-generated />
using FinanceService.Data;
using FinanceService.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FinanceService.Migrations;

[DbContext(typeof(FinanceDbContext))]
[Migration("20260611043800_AddCashPaymentConfirmation")]
partial class AddCashPaymentConfirmation
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("FinanceService.Domain.Entities.Payment", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<decimal>("Amount")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            b.Property<decimal?>("AmountReceived")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            b.Property<DateTime?>("ApprovedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("BranchId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<DateTime?>("CancelledAt")
                .HasColumnType("timestamp with time zone");

            b.Property<decimal?>("ChangeAmount")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Currency")
                .IsRequired()
                .ValueGeneratedOnAdd()
                .HasMaxLength(3)
                .HasColumnType("character varying(3)")
                .HasDefaultValue("MXN");

            b.Property<string>("CustomerAccountId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<string>("OrderId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<string>("Provider")
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<string>("ProviderReference")
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<string>("RejectionReason")
                .HasMaxLength(512)
                .HasColumnType("character varying(512)");

            b.Property<DateTime?>("RejectedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("RestaurantId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<PaymentStatus>("Status")
                .ValueGeneratedOnAdd()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)")
                .HasDefaultValue(PaymentStatus.Pending)
                .HasConversion<string>();

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("OrderId")
                .IsUnique();

            b.ToTable("payments", (string)null);
        });
#pragma warning restore 612, 618
    }
}
