server.port=8080
spring.application.name=api-gateway
management.endpoints.web.exposure.include=health,info

# identity-service
spring.cloud.gateway.server.webmvc.routes[0].id=identity-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

# catalog-service
spring.cloud.gateway.server.webmvc.routes[1].id=catalog-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/catalog/**

# finance-service
spring.cloud.gateway.server.webmvc.routes[2].id=finance-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/finance/**

# notification-service
spring.cloud.gateway.server.webmvc.routes[3].id=notification-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/notifications/**

# order-service
spring.cloud.gateway.server.webmvc.routes[4].id=order-service
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/orders/**

# recommendation-service
spring.cloud.gateway.server.webmvc.routes[5].id=recommendation-service
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/recommendations/**

# reports-python
spring.cloud.gateway.server.webmvc.routes[6].id=reports-python
spring.cloud.gateway.server.webmvc.routes[6].uri=http://localhost:8000
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/reports/**